mp:
  messaging:
    outgoing:
      incoming-channel:
        connector: smallrye-kafka
        topic: "incoming"
        value:
          serializer: org.apache.kafka.common.serialization.StringSerializer
    incoming:
      outgoing-channel:
        connector: smallrye-kafka
        topic: "outgoing"
        auto:
          offset:
            reset: "earliest"
        value:
          deserializer: org.apache.kafka.common.serialization.StringDeserializer

kafka:
  bootstrap:
    servers: localhost:9092

# OpenTelemetry configuration for metrics
quarkus:
  application:
    name: kafka-producer
  log:
    console:
      format: "%d{HH:mm:ss} %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n"
  otel:
    exporter:
      otlp:
        endpoint: http://localhost:4317
    metrics:
      enabled: true
    logs:
        enabled: true