receivers:
  otlp:
    protocols:
      grpc:
      http:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'kafka'
          scrape_interval: 15s
          static_configs:
            - targets: ['kafka:9999']  # Updated to match JMX exporter port
              labels:
                application: 'kafka'

        - job_name: 'quarkus-applications'
          scrape_interval: 10s
          static_configs:
            - targets: ['producer:8080']
              labels:
                service_name: 'kafka-producer'
                application: 'quarkus'
            - targets: ['consumer:8080']
              labels:
                service_name: 'kafka-consumer'
                application: 'quarkus'

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024

exporters:
  prometheusremotewrite:
    endpoint: "http://victoriametrics:8428/api/v1/write"
    namespace: "otel"
    resource_to_telemetry_conversion:
      enabled: true
  logging:
    verbosity: detailed

service:
  pipelines:
    metrics:
      receivers: [otlp, prometheus]
      processors: [batch]
      exporters: [prometheusremotewrite, logging]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
