apiVersion: 1

datasources:
  - name: victoriametrics
    type: prometheus
    access: proxy
    url: http://victoriametrics:8428
    isDefault: true
    jsonData:
      timeInterval: 15s
      httpMethod: GET
